name: Release

on:
  push:
    tags:
      - v*
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'  # once a month
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:

  almalinux:
    name: Publish AlmaLinux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.cern.ch/${{ github.repository_owner }}/almalinux
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=true

      # needed to build multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to CERN registry
        uses: docker/login-action@v2
        with:
          registry: registry.cern.ch
          username: ${{ secrets.CERN_REGISTRY_USERNAME }}
          password: ${{ secrets.CERN_REGISTRY_PASSWORD }}

      - name: Publish AlmaLinux
        uses: docker/build-push-action@v3
        with:
          context: ./almalinux/
          file: ./almalinux/Dockerfile
          # support images for Intel and Apple Silicon processors
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  centos7:
    name: Publish CentOS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: CentOS 7 Python 3.6
            context: ./centos7/python3.6/
            file: ./centos7/python3.6/Dockerfile
            tag: 3.6

          - name: CentOS 7 Python 3.9
            context: ./centos7/python3.9/
            file: ./centos7/python3.9/Dockerfile
            tag: 3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to CERN registry
        uses: docker/login-action@v2
        with:
          registry: registry.cern.ch
          username: ${{ secrets.CERN_REGISTRY_USERNAME }}
          password: ${{ secrets.CERN_REGISTRY_PASSWORD }}

      - name: Publish ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ matrix.tag }}
